class AlreadyExecutedException(message: String?, val acc: Int) : Exception(message) {
}